### ISSUE TITLE
網路安全一問

### ISSUE THREAD

**Issue by The992255** [sky172839465/AMA_Frontend#1]
firebase有Authentication功能
設定的帳密登入後會得到一筆密碼
```
firebase.auth().signInWithEmailAndPassword(email, password)
            .then(() => {
                firebase.auth().currentUser.getIdToken()
                    .then((token: string) => this.token = token)
            });
```
再去Database設定安全性，只有該密碼才能訪問
`get('https://database.firebaseio.com/data.json?auth=' + token)`
然而這個token在JS中有被竊取的風險嗎?
要是知道token的話隨時都可以訪問該資料庫了

**Comment by sky172839465** [comment]
所謂的token是**有實效性**的金鑰，你不可能寫死放在JS裡，通常是用登入的帳號密碼去打一個可以取得新token的api，然後再拿這個token去做其他請求

**Comment by The992255** [comment]
了解

**Comment by sky172839465** [comment]
ok
