### ISSUE TITLE
{...arr, arr.arr, '4'}

### ISSUE THREAD

**Issue by The992255** [sky172839465/AMA_Frontend#2]
查不到這寫法該怎麼稱呼，所以標題只好這樣打
```
const aries = {
      aries: [
        '1', '2', '3'
      ]
    };
console.log({ ...aries, aries: [...aries.aries, '4'] }); //{aries: Array(4)}aries: (4) ["1", "2", "3", "4"] __proto__: Object
console.log({ aries: [...aries.aries, '4'] }); //同上
```
想問這兩種寫法有什麼不同的地方？
如果console.log1跟console.log2結果相同的話為什麼不用第二種？

**Comment by sky172839465** [comment]
1. 這個`...`是**ES6的語法**叫[Spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

2. 因為你現在最外層這個aries物件只有一個欄位，這是在拷貝物件，假設物件變這樣{aries: [], test:123, ans: 456}，透過spread syntax會幫你把其他欄位一起複製過來

3. 物件的欄位不要跟物件的變數名稱一樣

**Comment by The992255** [comment]
了解
那以我的例子來看，`{ ...aries, aries: [...aries.aries, '4'] }`是比較好的寫法嗎？
因為要是給aries新增更多欄位，用這個寫法也會一起拷貝過來
然而使用`{ aries: [...aries.aries, '4'] }`還是只會出拷貝aries的欄位的值，其他欄位就不會拷貝了

**Comment by sky172839465** [comment]
很難說哪個好，要先看需求是什麼

**Comment by The992255** [comment]
OK
